server:
  port: 9999
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClass: org.h2.Driver
    username: sa
    password: ~

  h2:
    console:
      enabled: true
      path: /h2
